### ISSUE TITLE
Requires com.whatsapp.sticker.READ or grantUriPermission() Error

### ISSUE THREAD

**Issue by Ferdari** [WhatsApp/stickers#537] opened 2019-08-07 19:23 UTC
Im receiving this error on some devices, the permission is already on the Manifest:

`<provider
    android:name="${applicationId}.starter$MyContentProvider"
    android:authorities="${applicationId}.stickercontentprovider"
    android:enabled="true"
    android:exported="true"
    android:readPermission="com.whatsapp.sticker.READ" />
)`

![67792660_461991511303531_8126262373834031104_n](https://user-images.githubusercontent.com/14990241/62651381-71263e80-b91e-11e9-95a7-eb36e55e6e15.jpg)

Error:
`Validation-Error: Permission Denial: reading app.packagexxxxx uri content: xxxxxxx Requires com.whatsapp.sticker.READ or grantUriPermission()`

As said, only happens on some devices, this time happened on **Android 9 ZTE Vita**

**Comment by simonzhexu** [comment] 2019-08-19 18:39
I will look into it. Thanks.

**Comment by BattleShipPark** [comment] 2019-11-21 09:33
I have same errors. Not every user has this problem, only some users have.

**Comment by runnableapps** [comment] 2020-03-01 17:39
> 
> 
> I will look into it. Thanks.

Any news on this problem?

**Comment by NiaNingXue** [comment] 2020-09-25 11:51
same issue

**Comment by Noxware** [comment] 2020-12-21 21:54
I experienced the same problem with a flutter package called [flutter_whatsapp_stickers](https://github.com/vincekruger/flutter_whatsapp_stickers). The problem occurred when whatsapp was installed in my sd card. Moving it back to the internal storage fixed the problem but needing to ask each user to move whatsapp back to the internal storage is not a true fix.

**Closed** 2021-12-30 20:02 UTC
Labels: Android

**Comment by hamadzaheen** [comment] 2022-01-24 11:06
has anyone solved this problem ?

**Comment by dataozhang** [comment] 2022-07-24 08:14
I don't know how the error happend. I receive thounds of log: .... requires com.whatsapp.sticker.READ, or grantUriPermission(), I also try install the whatsapp in SD card, but i can't reproduce  such error. Anyone solved such problem now?

**Comment by Kabalea** [comment] 2022-11-15 12:36
J'ai besoin d'une autorisation de sticker
