### ISSUE TITLE
Stickers was disappeared after 2 days

### ISSUE THREAD

**Issue by Darsh23** [WhatsApp/stickers#559] opened 2019-10-23 13:45 UTC
In this week i get a mass of asks because the user's when try to add stickers and pass 2 days it disappeared automatically from WhatsApp stickers list and they needed to add them again from application
I wasn't push any updates or change any code in this period 

Where's the proplem now ?

**Comment by simonzhexu** [comment] 2019-10-24 00:14
there was a bug, it has been fixed, have your users upgrade WhatsApp.

Sorry about that.

Tell me your play store URL if the issue is not resolved.

**Comment by ndanielvega** [comment] 2019-10-27 05:41
Hi! I also have that problem but I still do not see any update in the Play Store, in which version of whatsapp is this bug fixed? I currently have version 2.19.291

**Comment by louislam** [comment] 2019-10-28 09:22
Similar to op, i got a lot of complains about this problem.

Most of them are Huawei Android phone users.
For me, I do not have the problem, I am using ASUS Zenfone 6 (Android 9) and WhatsApp 2.19.291

**Comment by MarvinJWendt** [comment] 2019-10-28 13:45
@ndanielvega @louislam 
Please make sure that your app is using the latest version of this repository.
And that your users are using the latest WhatsApp version.

If it still fails, please open a new Issue with some error logs, so that we can debug that :)

**Comment by simonzhexu** [comment] 2019-10-28 14:58
The fix is in 2.19.292 and up.

**Comment by simonzhexu** [comment] 2019-11-01 05:55
You should have a new version now.

Updating WhatsApp is enough. However, I advise you update your app to latest version of this repo as that will give you some benefit to some other things we currently are working on.

**Closed** 2019-11-12 17:47 UTC
Labels: Android
