### ISSUE TITLE
[iOS] One of the stickers in this sticker pack has an invalid asset

### ISSUE THREAD

**Issue by Jeanno** [WhatsApp/stickers#1011] opened 2024-05-05 15:58 UTC
**Specifications**  
OS Version: iOS 17.x
Device Manufacturer: Apple
WhatsApp version: >= 24.9.1

**Stickers**
- [x] My stickers do comply with the sticker requirements (512x512 and < 100 KB)
- [x] My tray icon does comply with the requirements (96x96 and < 50 KB)
- [x] I am using **WebP** images for stickers.
- [x] I am using **PNG** images for stickers.

**Problem Description**  
Users start to receive the error message "One of the stickers in this sticker pack has an invalid asset" since the WhatsApp update 24.9.1. Stickers used to be able to added to WhatsApp (before 24.9.1) now throws this error message instead.

**Reproduction Steps**  
1) Add stickers from this page to WhatsApp
https://www.sigstick.com/pack/dCWpSTPcC1xR9uKnKEHf

2) The error message "One of the stickers in this sticker pack has an invalid asset" is shown

Note: Not all stickers can reproduce the error.

**Links**  
Example stickers that experience this problem.
https://www.sigstick.com/pack/dCWpSTPcC1xR9uKnKEHf

**Comment by Jeanno** [comment] 2024-05-06 18:05
@tomw Would you please also take a look at this?

**Comment by Jeanno** [comment] 2024-05-10 01:19
Looks like this problem has spread to Android. Is it because of a shared webp decoder between iOS and Android WhatsApp?

**Comment by tomw** [comment] 2024-05-14 14:57
Thanks, we're investigating

**Comment by Jeanno** [comment] 2024-05-14 17:49
> Thanks, we're investigating
Not all stickers in that set has the problem. I tried to separately install them and only a few of them can trigger the error.

I have a few more other stickers with problem. Let me know if you need them.

**Comment by MarsVard** [comment] 2024-05-17 04:00
Any updates on this?

**Comment by Jeanno** [comment] 2024-05-17 16:48
> Any updates on this?

Are you experiencing the same?

**Comment by tomw** [comment] 2024-05-20 15:37
Yes, we can reproduce the problem and are actively working on fixing it. Thanks for the report & test case.

**Comment by lijianyou-Herve** [comment] 2024-05-22 11:47
> 是的，我们可以重现该问题并正在积极修复它。感谢您的报告和测试用例。

Can you tell me which part of the encoding specification doesn't meet. I hope I can deal with it as much as possible, so that I don't need to wait for you to deal with it, which is very important for our project, because the negative reviews of apps are increasing

**Comment by lijianyou-Herve** [comment] 2024-05-22 11:48
> Yes, we can reproduce the problem and are actively working on fixing it. Thanks for the report & test case.

Can you tell me which part of the encoding specification doesn't meet. I hope I can deal with it as much as possible, so that I don't need to wait for you to deal with it, which is very important for our project, because the negative reviews of apps are increasing

**Comment by tomw** [comment] 2024-05-22 16:45
The fix is on its way, and will be in the 2.24.11 releases. The chunk size of ALPH was seen to be unusually small (2 bytes), which we've rarely seen before, exposing a corner case bug in our code. Hope that helps. Sorry we can't get the fix out faster – these are our usual app release timings.

**Closed by tomw** 2024-05-22 16:45 UTC
Labels: iOS

**Comment by Jeanno** [comment] 2024-06-03 04:39
Since there's no update for 2 weeks, is there a date for WhatsApp to release v2.24.11? Hopefully this is coming soon (not blizzard soon)

**Comment by Jeanno** [comment] 2025-03-01 18:45
I opened a new issue.

https://github.com/WhatsApp/stickers/issues/1083
