### ISSUE TITLE
[Android] Animated stickers have stopped working

### ISSUE THREAD

**Issue by luizflb** [WhatsApp/stickers#749] opened 2021-03-05 19:00 UTC
**Specifications**  
OS Version: Android 7.1.1
Device Manufacturer: Motorola

**Stickers**
- [x] My stickers do comply with the sticker requirements (512x512 and < 100 KB) (< 500kb)
- [x] My tray icon does comply with the requirements (96x96 and < 50 KB)
- [x] I am using **WebP** images for stickers.
- [ ] I am using **PNG** images for stickers.

**Problem Description**  
My app is from Brazil, the stickers when they were released were working, I imported from my app quietly to whatsapp, but whatsapp has updated and now it is not accepting animated stickers anymore, it gives the error "there is a problem with this sticker pack and it is not possible to add it to Whatsapp ", and in some sticker apps that you could create animated it also doesn't work anymore with the following error" total duratioshould be under
10000ms ", on iOS it still works the same stickers, I didn't understand what they did with Android!

**Links**  
functional application on iOS, (WhatsApp version: 2.21.40.13): https://apps.apple.com/br/app/sticker-maker-studio/id1443326857 
apps that don't work on Android and previously worked, (whatsapp version: 2.21.4.22): https://play.google.com/store/apps/details?id=com.animatedstickers.maker
https://play.google.com/store/apps/details?id=com.sticker.pacotaodememes

**Comment by santi-petersen** [comment] 2021-03-05 19:08
Duplicate of #718

**Closed** 2021-06-08 22:48 UTC
Labels: Android
