### ISSUE TITLE
[Android] Unable to import animated webp stickers into WhatsApp

### ISSUE THREAD

**Issue by laggykiller** [WhatsApp/stickers#998] opened 2024-01-17 19:16 UTC
**Specifications**  
OS Version: Android 13
Device Manufacturer: Samsung
WhatsApp Version: 2.24.2.13

**Stickers**
- [X] My stickers do comply with the sticker requirements (512x512 and < 100 KB)
- [X] My tray icon does comply with the requirements (96x96 and < 50 KB)
- [X] I am using **WebP** images for stickers.
- [ ] I am using **PNG** images for stickers.

**Problem Description**  
When importing animated webp stickers into WhatsApp, it fails with "There's a problem with this sticker pack and it can't be added to WhatsApp". I have tried two sticker applications already, both failing to do so. Updating previously working animated sticker pack also do not work with same error message. Non-animated webp sticker packs seem not affected by this bug. I suspect something is wrong with WhatsApp recent update.

**Reproduction Steps**  
Try to import animated webp stickers into WhatsApp. 

**Head of Commit**
N/A

**Links**  
N/A

**Comment by santi-petersen** [comment] 2024-01-18 00:11
We have received many reports from our app users about this error in the last 4 days. Error occurs only with animated stickers. I can't reproduce it because I have WhatsApp version 2.23.25.83, but users with the version 2.24.2.13 can no longer add packs.

**Comment by santi-petersen** [comment] 2024-01-18 00:34
Same error in version 2.24.2.14 (Beta)

**Comment by MarsVard** [comment] 2024-01-19 07:12
I tried this with the demo stickers in this repo, still receiving the same error claiming the stickers are less than 8ms per frame.

It started occurring in the beta version of WhatsApp. I'm assuming it's a bug in the beta that's unable to measure frame duration in webp.

**Comment by santi-petersen** [comment] 2024-01-22 17:39
Any update on this @simonzhexu ? **Please do not release this beta to production**, there have been similar bugs in WhatsApp Beta that reached production.
We have now many WhatsApp beta users who are rating low our app because of this bug.

**Comment by santi-petersen** [comment] 2024-01-23 16:59
I have tested each of the latest versions of WhatsApp, in 2.24.2.71 the error was fixed but it returned in 2.24.3.9 😔

2.24.2.13 ERROR
2.24.2.14 ERROR
2.24.2.16 ERROR
2.24.2.17 ERROR
2.24.2.20 ERROR
**2.24.2.71** OK (fixed!)
2.24.3.9 ERROR (came back)
2.24.3.10 ERROR

The error message is "frame duration for any frame should exceed 8 ms. sticker: ..." but there is nothing wrong with the webp frames durations.

**Comment by santi-petersen** [comment] 2024-01-25 15:21
Fixed in version 2.24.3.15!

**2.24.3.15** OK
**2.24.3.16** OK

**Comment by santi-petersen** [comment] 2024-01-26 13:36
@laggykiller , since the latest Beta versions of WhatsApp solved the problem, I think you can now close this issue.

**Closed** 2024-01-26 14:06 UTC
Labels: Android
