### ISSUE TITLE
Animated sticker - total animation duration should be under 10000 ms

### ISSUE THREAD

**Issue by runnableapps** [WhatsApp/stickers#773] opened 2021-04-09 17:39 UTC
Error:
Total animation duration should be under 10000 ms.

Sticker duration less than 1000ms. 
Always shows that first sticker in sticker pack has invalid duration

**Comment by santi-petersen** [comment] 2021-04-09 18:13
Duplicate of #718. Add your device model and app link or zip with the stickers to the original thread.

**Comment by MarvinJWendt** [comment] 2021-05-03 16:02
Duplicate of #718

**Closed by MarvinJWendt** 2021-05-03 16:02 UTC
Labels: Android
