### ISSUE TITLE
[Android] Can't not add more than 2 Stickerpacks, otherwise App "keep stopping"

### ISSUE THREAD

**Issue by modys** [WhatsApp/stickers#628] opened 2020-04-28 10:39 UTC
**Specifications**  
OS Version: [FILL IN]
Device Manufacturer: [FILL IN]

**Stickers**
- [ ] My stickers do comply with the sticker requirements (512x512 and < 100 KB)
- [ ] My tray icon does comply with the requirements (96x96 and < 50 KB)
- [ ] I am using **WebP** images for stickers.
- [ ] I am using **PNG** images for stickers.

(All checked and done).

**Problem Description**  
[FILL IN WITH DETAILED DESCRIPTION OF THE PROBLEM]

App working fine until i try to add more than 2 packs/directories to my app, no errors in "contents.json" are noticeable. If i remove 3 pack, everything working fine again.  Also i tried to change stickers, in this 3 pack, but without success,.. i checked already all trey icons, and Sticker file aswell, everything correspond the ruls. I m not a senior developer in Android enviroment, may you can give me some tips how to, change limit for adding packs.

Thx!
Scrennshot with contents.json i do attach it here may it can help.

**Reproduction Steps**  
[FILL IN WITH DETAILED REPRODUCTION STEPS]

{
  "android_play_store_link": "",
  "ios_app_store_link": "",
  "sticker_packs": [
    {
      "identifier": "1",
      "name": "Володя Яковлев",
      "publisher": "Sersch Codex",
      "tray_image_file": "volodya.png",
      "image_data_version": "1",
      "avoid_cache": false,
      "publisher_email": "support@birbel.com",
      "publisher_website": "https://birbel.com",
      "privacy_policy_website": "https://birbel.com",
      "license_agreement_website": "https://birbel.com",
      "stickers": [
        {
          "image_file": "1.webp",
          "emojis": [
            "☕",
            "🙂"
          ]
        },
        {
          "image_file": "2.webp",
          "emojis": [
            "😄",
            "😀"
          ]
        },
        {
          "image_file": "3.webp",
          "emojis": [
            "😆",
            "😂"
          ]
        },
        {
          "image_file": "4.webp",
          "emojis": [
            "😩",
            "😰"
          ]
        },
        {
          "image_file": "5.webp",
          "emojis": [
            "😭",
            "💧"
          ]
        },
        {
          "image_file": "6.webp",
          "emojis": [
            "😍",
            "♥"
          ]
        },
        {
          "image_file": "7.webp",
          "emojis": [
            "💔",
            "👎"
          ]
        },
        {
          "image_file": "8.webp",
          "emojis": [
            "😍",
            "💑"
          ]
        },
        {
          "image_file": "9.webp",
          "emojis": [
            "😘",
            "🍪"
          ]
        },
        {
          "image_file": "10.webp",
          "emojis": [
            "🤔",
            "😐"
          ]
        },
        {
          "image_file": "11.webp",
          "emojis": [
            "😱",
            "😵"
          ]
        },
        {
          "image_file": "12.webp",
          "emojis": [
            "😡",
            "😠"
          ]
        },
        {
          "image_file": "13.webp",
          "emojis": [
            "❓",
            "🤔"
          ]
        },
        {
          "image_file": "14.webp",
          "emojis": [
            "🌈",
            "😜"
          ]
        },
        {
          "image_file": "15.webp",
          "emojis": [
            "💻",
            "😩"
          ]
        },
        {
          "image_file": "16.webp",
          "emojis": [
            "😡",
            "😤"
          ]
        },
        {
          "image_file": "17.webp",
          "emojis": [
            "😩",
            "😨"
          ]
        },
        {
          "image_file": "18.webp",
          "emojis": [
            "💻",
            "🌃"
          ]
        },
        {
          "image_file": "19.webp",
          "emojis": [
            "🎉",
            "✨"
          ]
        },
        {
          "image_file": "20.webp",
          "emojis": [
            "🤮",
            "👎"
          ]
        },
        {
          "image_file": "21.webp",
          "emojis": [
            "🖐",
            "🙋"
          ]
        },
        {
          "image_file": "22.webp",
          "emojis": [
            "🖐",
            "👋"
          ]
        },
        {
          "image_file": "23.webp",
          "emojis": [
            "🍵",
            "😌"
          ]
        },
        {
          "image_file": "24.webp",
          "emojis": [
            "📱",
            "😦"
          ]
        },
        {
          "image_file": "25.webp",
          "emojis": [
            "🔋",
            "😵"
          ]
        },
        {
          "image_file": "26.webp",
          "emojis": [
            "🖐",
            "👋"
          ]
        },
        {
          "image_file": "27.webp",
          "emojis": [
            "🍵",
            "😌"
          ]
        },
        {
          "image_file": "28.webp",
          "emojis": [
            "📱",
            "😦"
          ]
        },
        {
          "image_file": "29.webp",
          "emojis": [
            "🔋",
            "😵"
          ]
        },
        {
          "image_file": "30.webp",
          "emojis": [
            "🔋",
            "😵"
          ]
        }
      ]
    },
    {
      "identifier": "2",
      "name": "Бородач",
      "publisher": "Sersch Codex",
      "tray_image_file": "boroda.png",
      "image_data_version": "1",
      "avoid_cache": false,
      "publisher_email": "support@birbel.com",
      "publisher_website": "https://birbel.com",
      "privacy_policy_website": "https://birbel.com",
      "license_agreement_website": "https://birbel.com",
      "stickers": [
        {
          "image_file": "boroda_1.webp",
          "emojis": [
            "☕",
            "🙂"
          ]
        },
        {
          "image_file": "boroda_2.webp",
          "emojis": [
            "😄",
            "😀"
          ]
        },
        {
          "image_file": "boroda_3.webp",
          "emojis": [
            "😆",
            "😂"
          ]
        },
        {
          "image_file": "boroda_4.webp",
          "emojis": [
            "😩",
            "😰"
          ]
        },
        {
          "image_file": "boroda_5.webp",
          "emojis": [
            "😭",
            "💧"
          ]
        },
        {
          "image_file": "boroda_6.webp",
          "emojis": [
            "😍",
            "♥"
          ]
        },
        {
          "image_file": "boroda_7.webp",
          "emojis": [
            "💔",
            "👎"
          ]
        },
        {
          "image_file": "boroda_8.webp",
          "emojis": [
            "😍",
            "💑"
          ]
        },
        {
          "image_file": "boroda_9.webp",
          "emojis": [
            "😘",
            "🍪"
          ]
        },
        {
          "image_file": "boroda_10.webp",
          "emojis": [
            "🤔",
            "😐"
          ]
        },
        {
          "image_file": "boroda_11.webp",
          "emojis": [
            "😱",
            "😵"
          ]
        },
        {
          "image_file": "boroda_12.webp",
          "emojis": [
            "😡",
            "😠"
          ]
        },
        {
          "image_file": "boroda_13.webp",
          "emojis": [
            "❓",
            "🤔"
          ]
        },
        {
          "image_file": "boroda_14.webp",
          "emojis": [
            "🌈",
            "😜"
          ]
        },
        {
          "image_file": "boroda_15.webp",
          "emojis": [
            "💻",
            "😩"
          ]
        },
        {
          "image_file": "boroda_16.webp",
          "emojis": [
            "😡",
            "😤"
          ]
        },
        {
          "image_file": "boroda_17.webp",
          "emojis": [
            "😩",
            "😨"
          ]
        },
        {
          "image_file": "boroda_18.webp",
          "emojis": [
            "💻",
            "🌃"
          ]
        },
        {
          "image_file": "boroda_19.webp",
          "emojis": [
            "🎉",
            "✨"
          ]
        },
        {
          "image_file": "boroda_20.webp",
          "emojis": [
            "🤮",
            "👎"
          ]
        },
        {
          "image_file": "boroda_21.webp",
          "emojis": [
            "🖐",
            "🙋"
          ]
        },
        {
          "image_file": "boroda_22.webp",
          "emojis": [
            "🖐",
            "👋"
          ]
        },
        {
          "identifier": "3",
          "name": "Каха и Серго",
          "publisher": "Sersch Codex",
          "tray_image_file": "kacha.png",
          "image_data_version": "1",
          "avoid_cache": false,
          "publisher_email": "support@birbel.com",
          "publisher_website": "https://birbel.com",
          "privacy_policy_website": "https://birbel.com",
          "license_agreement_website": "https://birbel.com",
          "stickers": [
            {
              "image_file": "sochy_1.webp",
              "emojis": [
                "☕",
                "🙂"
              ]
            }
      ]
        }
      ]
    }
  ]
}

**Head of Commit**
[Do you have the latest commit from master? If not, please update your repo to the latest commit in master, and try again. If issue still occurs, please note down the commit hash (from this repo) here:]
[Commit hash]

**Links**  
[FILL IN PLAY STORE LINK AND/OR LINK TO SOURCE CODE ON GIT]

**Comment by MarvinJWendt** [comment] 2020-04-29 02:31
Duplicate of #629

**Closed by MarvinJWendt** 2020-04-29 02:31 UTC
Labels: Android
