### ISSUE TITLE
[Android] Caused by: java.lang.UnsatisfiedLinkError: couldn't find DSO to load: libstatic-webp.so

### ISSUE THREAD

**Issue by rebelholic** [WhatsApp/stickers#413] opened 2019-02-01 09:08 UTC
**Specifications**  
OS Version: Android 8
Device Manufacturer: Xiaomi MI 5

**Stickers**
- [Y ] My stickers do comply with the sticker requirements (512x512 and < 100 KB)
- [Y ] My tray icon does comply with the requirements (96x96 and < 50 KB)
- [Y ] I am using **WebP** images for stickers.

**Problem Description**  
App works perfectly well with emulator and also on mobile via USB. But when uploaded onto Google PlayStore using the Android App Bundle version and downloaded from PlayStore, the app kept shutting down. Can't even open the app! It force closes.

Log from Google Play Developer Console:

```
java.lang.RuntimeException: An error occurred while executing doInBackground()
	at android.os.AsyncTask$3.done(AsyncTask.java:325)
	at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:354)
	at java.util.concurrent.FutureTask.setException(FutureTask.java:223)
	at java.util.concurrent.FutureTask.run(FutureTask.java:242)
	at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:243)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
	at java.lang.Thread.run(Thread.java:760)
Caused by: java.lang.UnsatisfiedLinkError: couldn't find DSO to load: libstatic-webp.so caused by: dlopen failed: library "/system/lib/libstatic-webp.so" needed or dlopened by "/system/lib64/libnativeloader.so" is not accessible for the namespace "classloader-namespace"
	at com.facebook.soloader.SoLoader.b(Unknown Source)
	at com.facebook.soloader.SoLoader.a(Unknown Source)
	at com.facebook.soloader.SoLoader.a(Unknown Source)
	at com.facebook.soloader.SoLoader.a(Unknown Source)
	at com.facebook.imagepipeline.nativecode.d.a(Unknown Source)
	at com.facebook.animated.webp.WebPImage.a(Unknown Source)
	at com.baysoft.pocongjumpstickers.i.a(Unknown Source)
	at com.baysoft.pocongjumpstickers.i.a(Unknown Source)
	at com.baysoft.pocongjumpstickers.i.a(Unknown Source)
	at com.baysoft.pocongjumpstickers.h.a(Unknown Source)
	at com.baysoft.pocongjumpstickers.EntryActivity$a.a(Unknown Source)
	at com.baysoft.pocongjumpstickers.EntryActivity$a.doInBackground(Unknown Source)
	at android.os.AsyncTask$2.call(AsyncTask.java:305)
	at java.util.concurrent.FutureTask.run(FutureTask.java:237)
```

**Head of Commit**
https://github.com/WhatsApp/stickers/commit/cce98cc6ac390aa34c3eb3a3c04c746c732ce93a

**Links**  
https://play.google.com/store/apps/details?id=com.baysoft.pocongjumpstickers

I will send my apk/abb for investigation if you interested

**Comment by alexbertis** [comment] 2019-02-01 15:45
+1

**Comment by MarvinJWendt** [comment] 2019-02-01 23:30
Hey,
It seems like this is a duplicate of #410 

Sincerely,
Marvin Wendt

**Comment by simonzhexu** [comment] 2019-02-04 17:45
Sorry, guys, this turns out to be a problem with fresco, where app bundle is not well supported. This commit fixes it: https://github.com/WhatsApp/stickers/commit/00c372ea5e2534ff9279c7103a321a4212b0f579
The problem was that app bundle builds multiple dexes, but Fresco was only looking at one to find the so file. There were no problems with using apk to send to play store.

**Closed by simonzhexu** 2019-02-04 17:45 UTC
Labels: Android

**Comment by pratikbutani** [comment] 2019-02-28 12:42
For me updating following libraries get worked:

```
implementation 'com.facebook.fresco:fresco:1.12.1'
implementation 'com.facebook.fresco:webpsupport:1.12.1'
implementation 'com.facebook.fresco:animated-webp:1.12.1'
```

Answered here : https://stackoverflow.com/a/54925969/1318946 :+1:

**Comment by hardapps1692** [comment] 2019-06-13 15:42
> For me updating following libraries get worked:
> 
> ```
> implementation 'com.facebook.fresco:fresco:1.12.1'
> implementation 'com.facebook.fresco:webpsupport:1.12.1'
> implementation 'com.facebook.fresco:animated-webp:1.12.1'
> ```
> 
> Answered here : https://stackoverflow.com/a/54925969/1318946

This solution not working. I have updated with version 1.13.0

**Comment by pratikbutani** [comment] 2019-06-14 06:41
> > For me updating following libraries get worked:
> > ```
> > implementation 'com.facebook.fresco:fresco:1.12.1'
> > implementation 'com.facebook.fresco:webpsupport:1.12.1'
> > implementation 'com.facebook.fresco:animated-webp:1.12.1'
> > ```
> > 
> > 
> > Answered here : https://stackoverflow.com/a/54925969/1318946
> 
> This solution not working. I have updated with version 1.13.0

That means you have to be updated every time.

**Comment by hardapps1692** [comment] 2019-06-14 13:59
> > > For me updating following libraries get worked:
> > > ```
> > > implementation 'com.facebook.fresco:fresco:1.12.1'
> > > implementation 'com.facebook.fresco:webpsupport:1.12.1'
> > > implementation 'com.facebook.fresco:animated-webp:1.12.1'
> > > ```
> > > 
> > > 
> > > Answered here : https://stackoverflow.com/a/54925969/1318946
> > 
> > 
> > This solution not working. I have updated with version 1.13.0
> 
> That means you have to be updated every time.

I have updated in the app but the same issue. Especially in Samsung devices

**Comment by SilverFoxA** [comment] 2019-08-02 12:56
Confirming. The issue still persists. Using the latest `fresco` version

   
    implementation 'com.facebook.fresco:fresco:2.0.0'
    implementation 'com.facebook.fresco:webpsupport:2.0.0'
    implementation 'com.facebook.fresco:animated-webp:2.0.0'
    implementation 'com.facebook.fresco:animated-base:2.0.0'
```

**Comment by dariotrombello** [comment] 2019-08-11 11:10
I also get this crash on my S9 with on play store released appbundle.
