### ISSUE TITLE
[Android] Validation failed:sticker file might be corrupted or invalid, sticker: /stickers_asset/1716175479/Anim_6.webp

### ISSUE THREAD

**Issue by lijianyou-Herve** [WhatsApp/stickers#1017] opened 2024-05-20 06:31 UTC
**Specifications**  
OS Version: [FILL IN]
Device Manufacturer: [FILL IN]

**Stickers**
- [x] My stickers do comply with the sticker requirements (512x512 and < 100 KB)
- [x] My tray icon does comply with the requirements (96x96 and < 50 KB)
- [x] I am using **WebP** images for stickers.
- [x] I am using **PNG** images for stickers.

**Problem Description**  
[FILL IN WITH DETAILED DESCRIPTION OF THE PROBLEM]

**Reproduction Steps**  
[FILL IN WITH DETAILED REPRODUCTION STEPS]

**Head of Commit**
[Do you have the latest commit from master? If not, please update your repo to the latest commit in master, and try again. If issue still occurs, please note down the commit hash (from this repo) here:]
[Commit hash]

**Links**  
[FILL IN PLAY STORE LINK AND/OR LINK TO SOURCE CODE ON GIT]

only anim sticker 

we can add to whatsapp in WhatsApp 2.24.8.86 

but after WhatsApp 2.24.9.78 . we can't add。

this is error message:

Validation failed:sticker file might be corrupted or invalid, sticker: /stickers_asset/1716175479/Anim_6.webp

whats can i do to fix this problem

**Comment by Jeanno** [comment] 2024-05-22 06:57
Possibly a duplicate of https://github.com/WhatsApp/stickers/issues/1011

**Comment by lijianyou-Herve** [comment] 2024-05-22 07:43
> [可能是#1011](https://github.com/WhatsApp/stickers/issues/1011)的重复[](https://github.com/WhatsApp/stickers/issues/1011)
yes,thats a same problem!

**Comment by Korogba** [comment] 2024-05-22 08:12
Thanks for reporting. This should be fixed in the next release. Please re-open if you can still reproduce then

**Comment by Korogba** [comment] 2024-05-22 08:13
Duplicate of #1011

**Closed** 2024-05-22 08:13 UTC
Labels: Android
